/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedProjetosRouteImport } from './routes/_authenticated/projetos'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedTarefasTaskIdRouteImport } from './routes/_authenticated/tarefas_.$taskId'
import { Route as AuthenticatedProjetosNovoRouteImport } from './routes/_authenticated/projetos_.novo'
import { Route as AuthenticatedProjetosIaRouteImport } from './routes/_authenticated/projetos_.ia'
import { Route as AuthenticatedProjetosProjectIdRouteImport } from './routes/_authenticated/projetos_.$projectId'
import { Route as AuthenticatedClientesNovoRouteImport } from './routes/_authenticated/clientes_.novo'
import { Route as AuthenticatedProjetosProjectIdEditarRouteImport } from './routes/_authenticated/projetos_.$projectId.editar'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjetosRoute = AuthenticatedProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTarefasTaskIdRoute =
  AuthenticatedTarefasTaskIdRouteImport.update({
    id: '/tarefas_/$taskId',
    path: '/tarefas/$taskId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjetosNovoRoute =
  AuthenticatedProjetosNovoRouteImport.update({
    id: '/projetos_/novo',
    path: '/projetos/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjetosIaRoute = AuthenticatedProjetosIaRouteImport.update({
  id: '/projetos_/ia',
  path: '/projetos/ia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjetosProjectIdRoute =
  AuthenticatedProjetosProjectIdRouteImport.update({
    id: '/projetos_/$projectId',
    path: '/projetos/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesNovoRoute =
  AuthenticatedClientesNovoRouteImport.update({
    id: '/clientes_/novo',
    path: '/clientes/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjetosProjectIdEditarRoute =
  AuthenticatedProjetosProjectIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedProjetosProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRouteWithChildren
  '/projetos/ia': typeof AuthenticatedProjetosIaRoute
  '/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/tarefas/$taskId': typeof AuthenticatedTarefasTaskIdRoute
  '/projetos/$projectId/editar': typeof AuthenticatedProjetosProjectIdEditarRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/projetos': typeof AuthenticatedProjetosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/': typeof AuthenticatedIndexRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/projetos/$projectId': typeof AuthenticatedProjetosProjectIdRouteWithChildren
  '/projetos/ia': typeof AuthenticatedProjetosIaRoute
  '/projetos/novo': typeof AuthenticatedProjetosNovoRoute
  '/tarefas/$taskId': typeof AuthenticatedTarefasTaskIdRoute
  '/projetos/$projectId/editar': typeof AuthenticatedProjetosProjectIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/projetos': typeof AuthenticatedProjetosRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clientes_/novo': typeof AuthenticatedClientesNovoRoute
  '/_authenticated/projetos_/$projectId': typeof AuthenticatedProjetosProjectIdRouteWithChildren
  '/_authenticated/projetos_/ia': typeof AuthenticatedProjetosIaRoute
  '/_authenticated/projetos_/novo': typeof AuthenticatedProjetosNovoRoute
  '/_authenticated/tarefas_/$taskId': typeof AuthenticatedTarefasTaskIdRoute
  '/_authenticated/projetos_/$projectId/editar': typeof AuthenticatedProjetosProjectIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/clientes'
    | '/projetos'
    | '/tarefas'
    | '/clientes/novo'
    | '/projetos/$projectId'
    | '/projetos/ia'
    | '/projetos/novo'
    | '/tarefas/$taskId'
    | '/projetos/$projectId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/clientes'
    | '/projetos'
    | '/tarefas'
    | '/'
    | '/clientes/novo'
    | '/projetos/$projectId'
    | '/projetos/ia'
    | '/projetos/novo'
    | '/tarefas/$taskId'
    | '/projetos/$projectId/editar'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/clientes'
    | '/_authenticated/projetos'
    | '/_authenticated/tarefas'
    | '/_authenticated/'
    | '/_authenticated/clientes_/novo'
    | '/_authenticated/projetos_/$projectId'
    | '/_authenticated/projetos_/ia'
    | '/_authenticated/projetos_/novo'
    | '/_authenticated/tarefas_/$taskId'
    | '/_authenticated/projetos_/$projectId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projetos': {
      id: '/_authenticated/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof AuthenticatedProjetosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tarefas_/$taskId': {
      id: '/_authenticated/tarefas_/$taskId'
      path: '/tarefas/$taskId'
      fullPath: '/tarefas/$taskId'
      preLoaderRoute: typeof AuthenticatedTarefasTaskIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projetos_/novo': {
      id: '/_authenticated/projetos_/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof AuthenticatedProjetosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projetos_/ia': {
      id: '/_authenticated/projetos_/ia'
      path: '/projetos/ia'
      fullPath: '/projetos/ia'
      preLoaderRoute: typeof AuthenticatedProjetosIaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projetos_/$projectId': {
      id: '/_authenticated/projetos_/$projectId'
      path: '/projetos/$projectId'
      fullPath: '/projetos/$projectId'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes_/novo': {
      id: '/_authenticated/clientes_/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AuthenticatedClientesNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projetos_/$projectId/editar': {
      id: '/_authenticated/projetos_/$projectId/editar'
      path: '/editar'
      fullPath: '/projetos/$projectId/editar'
      preLoaderRoute: typeof AuthenticatedProjetosProjectIdEditarRouteImport
      parentRoute: typeof AuthenticatedProjetosProjectIdRoute
    }
  }
}

interface AuthenticatedProjetosProjectIdRouteChildren {
  AuthenticatedProjetosProjectIdEditarRoute: typeof AuthenticatedProjetosProjectIdEditarRoute
}

const AuthenticatedProjetosProjectIdRouteChildren: AuthenticatedProjetosProjectIdRouteChildren =
  {
    AuthenticatedProjetosProjectIdEditarRoute:
      AuthenticatedProjetosProjectIdEditarRoute,
  }

const AuthenticatedProjetosProjectIdRouteWithChildren =
  AuthenticatedProjetosProjectIdRoute._addFileChildren(
    AuthenticatedProjetosProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedProjetosRoute: typeof AuthenticatedProjetosRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientesNovoRoute: typeof AuthenticatedClientesNovoRoute
  AuthenticatedProjetosProjectIdRoute: typeof AuthenticatedProjetosProjectIdRouteWithChildren
  AuthenticatedProjetosIaRoute: typeof AuthenticatedProjetosIaRoute
  AuthenticatedProjetosNovoRoute: typeof AuthenticatedProjetosNovoRoute
  AuthenticatedTarefasTaskIdRoute: typeof AuthenticatedTarefasTaskIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedProjetosRoute: AuthenticatedProjetosRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientesNovoRoute: AuthenticatedClientesNovoRoute,
  AuthenticatedProjetosProjectIdRoute:
    AuthenticatedProjetosProjectIdRouteWithChildren,
  AuthenticatedProjetosIaRoute: AuthenticatedProjetosIaRoute,
  AuthenticatedProjetosNovoRoute: AuthenticatedProjetosNovoRoute,
  AuthenticatedTarefasTaskIdRoute: AuthenticatedTarefasTaskIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
